### ISSUE TITLE
这是什么问题， 换一台机器运行就出现了这个错误。 所有列表都500错误。

### ISSUE THREAD

**Issue by jackrebel** [dotnetcore/WTM#114]
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST http://localhost:60647/_Admin/ActionLog/Search application/x-www-form-urlencoded; charset=UTF-8 407
Microsoft.AspNetCore.Cors.Infrastructure.CorsService: Information: CORS policy execution failed.
Microsoft.AspNetCore.Cors.Infrastructure.CorsService: Information: Request origin http://localhost:60647 does not have permission to access the resource.
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {area = "_Admin", action = "Search", controller = "ActionLog"}. Executing controller action with signature System.String Search(WalkingTec.Mvvm.Mvc.Admin.ViewModels.ActionLogVMs.ActionLogListVM) on controller WalkingTec.Mvvm.Mvc.Admin.Controllers.ActionLogController (WalkingTec.Mvvm.Mvc.Admin).
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executing action method WalkingTec.Mvvm.Mvc.Admin.Controllers.ActionLogController.Search (WalkingTec.Mvvm.Mvc.Admin) - Validation state: Invalid
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.0.0 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: RowNumberPaging 
Microsoft.EntityFrameworkCore.Database.Command: Debug: Creating DbCommand for 'ExecuteReader'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Created DbCommand for 'ExecuteReader' (3ms).
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opening connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opened connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Command: Information: Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)
FROM [ActionLogs] AS [a]
Microsoft.EntityFrameworkCore.Database.Command: Debug: Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)
FROM [ActionLogs] AS [a]
Microsoft.EntityFrameworkCore.Database.Command: Debug: A data reader was disposed.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closing connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closed connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Creating DbCommand for 'ExecuteReader'.
Microsoft.EntityFrameworkCore.Database.Command: Debug: Created DbCommand for 'ExecuteReader' (7ms).
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opening connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Opened connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Command: Information: Executing DbCommand [Parameters=[@__p_0='?' (DbType = Int32), @__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [a].[ID], [a].[ModuleName], [a].[ITCode], [a].[ActionTime], [a].[ActionName], [a].[ActionUrl], [a].[Duration], [a].[IP], [a].[LogType], [a].[Remark], [a].[CreateBy], [a].[CreateTime], [a].[UpdateBy], [a].[UpdateTime]
FROM [ActionLogs] AS [a]
ORDER BY [a].[ActionTime] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
引发的异常:“Microsoft.Data.SqlClient.SqlException”(位于 Microsoft.Data.SqlClient.dll 中)
引发的异常:“Microsoft.Data.SqlClient.SqlException”(位于 Microsoft.Data.SqlClient.dll 中)
引发的异常:“Microsoft.Data.SqlClient.SqlException”(位于 Microsoft.Data.SqlClient.dll 中)
引发的异常:“Microsoft.Data.SqlClient.SqlException”(位于 Microsoft.Data.SqlClient.dll 中)
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (414ms) [Parameters=[@__p_0='?' (DbType = Int32), @__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [a].[ID], [a].[ModuleName], [a].[ITCode], [a].[ActionTime], [a].[ActionName], [a].[ActionUrl], [a].[Duration], [a].[IP], [a].[LogType], [a].[Remark], [a].[CreateBy], [a].[CreateTime], [a].[UpdateBy], [a].[UpdateTime]
FROM [ActionLogs] AS [a]
ORDER BY [a].[ActionTime] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
引发的异常:“Microsoft.Data.SqlClient.SqlException”(位于 Microsoft.EntityFrameworkCore.Relational.dll 中)
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closing connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Database.Connection: Debug: Closed connection to database 'diamond_db' on server '.'.
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'zs.DataContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): 'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
ClientConnectionId:c2218e78-0e35-49c8-85d3-f95677fcb02f
Error Number:102,State:1,Class:15

**Comment by liuliang-wt** [comment]
Microsoft.Data.SqlClient.SqlException (0x80131904): 'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。
这个错误指示你应该是使用了很老的sql server 2008，ef最少需要使用sql server 2012

**Comment by liuliang-wt** [comment]
2.x版本的框架中，可以在Appsettings文件中设置IsOldSqlServer=true来指定使用2008以前的sqlserver， 但是3.x版本的框架中，因为目前EF 3.0 不再继续支持老版本的sqlserver，所以如果用3.x版本的框架，至少需要使用sql server 2012
