### ISSUE TITLE
3.8.0 发布为单文件报错

### ISSUE THREAD

**Issue by h080620** [dotnetcore/WTM#443]
Unhandled exception. System.IO.FileLoadException:
 Could not load file or assembly 'WalkingTec.Mvvm.Core, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null'.
  The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'WalkingTec.Mvvm.Core, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null'
   at DrugGsp.Program.<>c.<CreateWebHostBuilder>b__1_0(HostBuilderContext hostingContext, ILoggingBuilder logging)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_1.<ConfigureLogging>b__1(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureLogging>b__0(HostBuilderContext context, IServiceCollection collection)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at DrugGsp.Program.Main(String[] args)

**Comment by liuliang-wt** [comment]
我实际测试了一下，没有发现这个问题

**Comment by h080620** [comment]
我是旧项目直接NUGET升级的包，发布为单文件报错
刚刚我在平台重新生成项目，发布为单文件 测试正常，然后将项目文件（Areas）拷到新项目在发布为单文件，测试没有问题
