### ISSUE TITLE
新建项目(.Net Core 3.1 +Vue + 多个项目), 运行起来不能登录

### ISSUE THREAD

**Issue by ToMakeSense** [dotnetcore/WTM#451]
下了模板，按照以下配置(.Net Core 3.1 +Vue + 多个项目)，运行起来不能登录
![image](https://user-images.githubusercontent.com/6244148/108630725-36084380-74a1-11eb-836a-53e2bd283535.png)

出错信息如下:
```log
System.InvalidOperationException: An exception was thrown while attempting to evaluate the LINQ query parameter expression 'value(WalkingTec.Mvvm.Admin.Api.AccountController+<>c__DisplayClass3_0).userid.ToLower()'.
---> System.NullReferenceException: Object reference not set to an instance of an object.
  at lambda_method(Closure )
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
  --- End of inner exception stack trace ---
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
  at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
  at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
  at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
  at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
  at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
  at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
  at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
  at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
  at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
  at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExtractParameters(Expression query, IParameterValues parameterValues, IDiagnosticsLogger`1 logger, Boolean parameterize, Boolean generateContextAccessors)
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
  at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
  at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
  at WalkingTec.Mvvm.Admin.Api.AccountController.Login(String userid, String password, Boolean rememberLogin, Boolean cookie)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()<br />--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()<br />--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
  at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
  at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
  at WalkingTec.Mvvm.Mvc.FrameworkServiceExtension.<>c__DisplayClass2_0.<<UseFrameworkService>b__0>d.MoveNext()<br />--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
  at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by ToMakeSense** [comment]
Http request 如下, 对比了swagger文档，应该是参数传错了: **account** --> **userid**, 望在源码里更正！ 
```http
POST /api/_Account/Login HTTP/1.1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

account=admin&password=000000
```

**Comment by ToMakeSense** [comment]
另外，登录进去以后，右上角下拉菜单的 `代码生成` 和 `API文档` 调转链接是写死的(7598)，运行起来需要手动改端口才能正常使用
```
<a v-if="isDev" target="_blank" href="http://localhost:7598/_codegen?ui=vue">
    <el-dropdown-item>{{$t('navbar.generation')}}</el-dropdown-item>
</a>
<a v-if="isDev" target="_blank" href="http://localhost:7598/swagger">
    <el-dropdown-item>{{$t('navbar.api')}}</el-dropdown-item>
</a>
```

**Comment by ToMakeSense** [comment]
退出登录也出错了，404

![image](https://user-images.githubusercontent.com/6244148/108631791-a49bd000-74a6-11eb-8277-98e70e9ee71c.png)

**Comment by liuliang-wt** [comment]
sorry， 3.1在生成项目时错误的使用了5.0的模板，目前已修复，重新生成项目就好了。感谢指正。
