### ISSUE TITLE
生成代码时提示提交失败

### ISSUE THREAD

**Issue by Jiaweimsg** [dotnetcore/WTM#490]
使用代码生成器生成代码时提示"提交失败", 但是代码和菜单已经生成, 不影响功能使用.

异常信息:
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      => SpanId:d7e2f1f65ebd324e, TraceId:bb6cbd2e240ae545a2d2dcb8cfb511d0, ParentId:0000000000000000 => ConnectionId:0HM9J12GNP7MR => RequestPath:/_CodeGen/DoGen RequestId:0HM9J12GNP7MR:00000008
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at WalkingTec.Mvvm.Mvc.CodeGenVM.GenerateAddFKModel(String keyname, Type t, List`1 exist)
         at WalkingTec.Mvvm.Mvc.CodeGenVM.GenerateTest()
         at WalkingTec.Mvvm.Mvc.CodeGenVM.DoGen()
         at WalkingTec.Mvvm.Mvc._CodeGenController.DoGen(CodeGenVM vm)
         at lambda_method475(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at WalkingTec.Mvvm.Mvc.WtmMiddleware.InvokeAsync(HttpContext context, IOptionsMonitor`1 configs)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

模型类:
`
public class PayOrder : PersistPoco
    {
        [Display(Name = "ID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public new uint ID { get; set; }

        [Display(Name = "外部订单号")]
        [StringLength(36)]
        public string OutTradeNo { get; set; }

        [Display(Name = "商品描述")]
        [StringLength(512)]
        public string Body { get; set; }

        [Display(Name = "商品标题")]
        [StringLength(512)]
        public string Subject { get; set; }

        [Display(Name = "订单金额")]
        public int TotalFee { get; set; }

        [Display(Name = "授权码")]
        [StringLength(64)]
        public string AuthCode { get; set; }

        [Display(Name = "支付方式")]
        public PaymentMethodEnum? PaymentMethod { get; set; }

        [Display(Name = "付款用户ID")]
        [StringLength(128)]
        public string BuyerId { get; set; }

        [Display(Name = "付款用户")]
        [StringLength(128)]
        public string Buyer { get; set; }

        [Display(Name = "交易号")]
        [StringLength(128)]
        public string TradeNo { get; set; }

        [Display(Name = "总金额")]
        public int TotalAmount { get; set; }

        [Display(Name = "实收金额")]
        public int ReceiptAmount { get; set; }

        [Display(Name = "用户支付金额")]
        public int BuyerPayAmount { get; set; }

        [Display(Name = "代金券金额")]
        public int CouponAmount { get; set; }

        [Display(Name = "收款用户ID")]
        [StringLength(128)]
        public string SellerId { get; set; }

        [Display(Name = "收款账号")]
        [StringLength(128)]
        public string Seller { get; set; }

        [Display(Name = "支付状态")]
        public PayStatusEnum? PayStatus { get; set; }

        [Display(Name = "操作员ID")]
        [StringLength(128)]
        public string OperatorId { get; set; }

        [Display(Name = "操作员名称")]
        [StringLength(128)]
        public string OperatorName { get; set; }

        [Display(Name = "错误信息")]
        [StringLength(1024)]
        public string ErrorMessage { get; set; }

        [Display(Name = "支付时间")]
        public DateTime? PayTime { get; set; }
    }

    public enum PayStatusEnum
    {
        [Display(Name = "创建中")]
        生成中,
        [Display(Name = "创建失败")]
        生成失败,
        [Display(Name = "待支付")]
        待支付,
        [Display(Name = "未支付")]
        未支付,
        [Display(Name = "支付成功")]
        支付成功,
        [Display(Name = "支付异常")]
        支付异常
    }

    public enum PaymentMethodEnum
    {
        [Display(Name = "微信支付")]
        Wechat,
        [Display(Name = "支付宝")]
        Alipay
    }

`

**Comment by liuliang-wt** [comment]
感觉是这里的问题：

[Display(Name = "收款用户ID")]



    [StringLength(128)]



    public string SellerId { get; set; }







    [Display(Name = "收款账号")]



    [StringLength(128)]



    public string Seller { get; set; }

框架的代码生成器会寻找 xxx，和xxxId这组模式的命名，认为是定义外键关系的，而你这个不是

发件人: ***@***.***>
发送时间: 2021年6月19日 18:01
收件人: ***@***.***>
抄送: ***@***.***>
主题: [dotnetcore/WTM] 生成代码时提示提交失败 (#490)


使用代码生成器生成代码时提示"提交失败", 但是代码和菜单已经生成, 不影响功能使用.

异常信息:
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1] => SpanId:d7e2f1f65ebd324e, TraceId:bb6cbd2e240ae545a2d2dcb8cfb511d0, ParentId:0000000000000000 => ConnectionId:0HM9J12GNP7MR => RequestPath:/_CodeGen/DoGen RequestId:0HM9J12GNP7MR:00000008 An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object. at WalkingTec.Mvvm.Mvc.CodeGenVM.GenerateAddFKModel(String keyname, Type t, List1 exist)
at WalkingTec.Mvvm.Mvc.CodeGenVM.GenerateTest()
at WalkingTec.Mvvm.Mvc.CodeGenVM.DoGen()
at WalkingTec.Mvvm.Mvc._CodeGenController.DoGen(CodeGenVM vm)
at lambda_method475(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(ResourceInvoker invoker)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at WalkingTec.Mvvm.Mvc.WtmMiddleware.InvokeAsync(HttpContext context, IOptionsMonitor1 configs) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

模型类:
`
public class PayOrder : PersistPoco
{
[Display(Name = "ID")]
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
// ReSharper disable once InconsistentNaming
public new uint ID { get; set; }

    [Display(Name = "外部订单号")]



    [StringLength(36)]



    public string OutTradeNo { get; set; }







    [Display(Name = "商品描述")]



    [StringLength(512)]



    public string Body { get; set; }







    [Display(Name = "商品标题")]



    [StringLength(512)]



    public string Subject { get; set; }







    [Display(Name = "订单金额")]



    public int TotalFee { get; set; }







    [Display(Name = "授权码")]



    [StringLength(64)]



    public string AuthCode { get; set; }







    [Display(Name = "支付方式")]



    public PaymentMethodEnum? PaymentMethod { get; set; }







    [Display(Name = "付款用户ID")]



    [StringLength(128)]



    public string BuyerId { get; set; }







    [Display(Name = "付款用户")]



    [StringLength(128)]



    public string Buyer { get; set; }







    [Display(Name = "交易号")]



    [StringLength(128)]



    public string TradeNo { get; set; }







    [Display(Name = "总金额")]



    public int TotalAmount { get; set; }







    [Display(Name = "实收金额")]



    public int ReceiptAmount { get; set; }







    [Display(Name = "用户支付金额")]



    public int BuyerPayAmount { get; set; }







    [Display(Name = "代金券金额")]



    public int CouponAmount { get; set; }







    [Display(Name = "收款用户ID")]



    [StringLength(128)]



    public string SellerId { get; set; }







    [Display(Name = "收款账号")]



    [StringLength(128)]



    public string Seller { get; set; }







    [Display(Name = "支付状态")]



    public PayStatusEnum? PayStatus { get; set; }







    [Display(Name = "操作员ID")]



    [StringLength(128)]



    public string OperatorId { get; set; }







    [Display(Name = "操作员名称")]



    [StringLength(128)]



    public string OperatorName { get; set; }







    [Display(Name = "错误信息")]



    [StringLength(1024)]



    public string ErrorMessage { get; set; }







    [Display(Name = "支付时间")]



    public DateTime? PayTime { get; set; }



}







public enum PayStatusEnum



{



    [Display(Name = "创建中")]



    生成中,



    [Display(Name = "创建失败")]



    生成失败,



    [Display(Name = "待支付")]



    待支付,



    [Display(Name = "未支付")]



    未支付,



    [Display(Name = "支付成功")]



    支付成功,



    [Display(Name = "支付异常")]



    支付异常



}







public enum PaymentMethodEnum



{



    [Display(Name = "微信支付")]



    Wechat,



    [Display(Name = "支付宝")]



    Alipay



}



`

―

**Comment by Jiaweimsg** [comment]
感谢, 问题已解决
