### ISSUE TITLE
The captcha doesn't show if deploy the app to the docker.

### ISSUE THREAD

**Issue by sheng-jie** [dotnetcore/WTM#50]
Here is the exception:
```
An unhandled exception has occurred while executing the request.
2019-09-05T09:07:51.55414483+08:00 System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
2019-09-05T09:07:51.554172912+08:00    at Interop.Libdl.dlopen(String fileName, Int32 flag)
2019-09-05T09:07:51.554189177+08:00    at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
2019-09-05T09:07:51.554197875+08:00    at System.Drawing.SafeNativeMethods.Gdip..cctor()
2019-09-05T09:07:51.55420546+08:00    --- End of inner exception stack trace ---
2019-09-05T09:07:51.554213804+08:00    at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
2019-09-05T09:07:51.554222023+08:00    at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
2019-09-05T09:07:51.554229964+08:00    at WalkingTec.Mvvm.Mvc._FrameworkController.GetVerifyCode()
```
And I found the reason is because microsoft/dotnet images do not contain the native libgdiplus library required by System.Drawing.

Here is the reference : [Can't use System.Drawing.Common in microsoft/dotnet:runtime](https://github.com/dotnet/dotnet-docker/issues/618)

So it will be good to generate Dockerfile when creating template project.

**Comment by alienwow** [comment]
感谢您的意见！我们将在下一个版本中添加。

Thank you for your comments, we will add in the next version.

**Comment by sheng-jie** [comment]
Thanks, Close this issue now.
