### ISSUE TITLE
https://wtmdoc.walkingtec.cn/setup 生成项目文件，但选择sqlite数据库的时候，生成的项目都跑不起来。

### ISSUE THREAD

**Issue by lovemory** [dotnetcore/WTM#520]
![image](https://user-images.githubusercontent.com/10230756/136900367-1d114b83-d3ff-4b0b-b88f-e1dff7aa0cbd.png)
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.AggregateException: One or more errors occurred. (Connection string keyword 'server' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.)
       ---> System.ArgumentException: Connection string keyword 'server' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.
         at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
         at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
         at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
         at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
         at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)

**Comment by liuliang-wt** [comment]
选择sqlite，你需要把连接字符串也改成sqlite可以识别的。你可以直接在项目的appsettings文件里改
