### ISSUE TITLE
页面传值必须继承BaseVM

### ISSUE THREAD

**Issue by Dysheng** [dotnetcore/WTM#99]
报错信息如下：
System.InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'WalkingTec.Mvvm.Core.BaseVM', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.List`1[DNH.Model.PProductInfo]'.
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)
   at lambda_method(Closure , ViewDataDictionary )
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.Activate(Object page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.

**Comment by liuliang-wt** [comment]
此问题已修复
